pipeline {
  agent any

  stages {
    stage('Build & (optionally) Test') {
      steps {
        // build using the POM inside the subfolder
        // keep tests enabled; if there are none, that's fine
        sh 'mvn -B -f BankAccount-Java/pom.xml -DskipTests=false clean test'
      }
      post {
        always {
          // publish results if any exist; don't fail if none
          junit testResults: 'BankAccount-Java/target/surefire-reports/*.xml',
                allowEmptyResults: true
        }
      }
    }

    stage('Package') {
      steps {
        // if you truly don’t want tests to run, flip -DskipTests=true here
        sh 'mvn -B -f BankAccount-Java/pom.xml -DskipTests package'
      }
    }

    stage('Archive Artifact') {
      steps {
        archiveArtifacts artifacts: 'BankAccount-Java/target/*.jar', fingerprint: true
      }
    }
  }
}
